version: 1

phases:
  setup:
    nixPkgs:
      - php82
      - php82Extensions.composer
      - php82Extensions.curl
      - php82Extensions.gd
      - php82Extensions.mbstring
      - php82Extensions.openssl
      - php82Extensions.xml
      - php82Extensions.zip
      - php82Extensions.pdo_mysql
  install:
    - composer install --no-dev --optimize-autoloader --no-scripts
  build:
    - php artisan optimize
    - php artisan storage:link
    - chmod -R 755 storage
    - chmod -R 755 bootstrap/cache

start: bash start.sh